### ISSUE TITLE
Wiiurpxtool initialization error

### ISSUE THREAD

**Issue by ebi-allen** [BullyWiiPlaza/RPL-Studio#2]
I'm getting an Wiiurpxtool initialization error.
The error message is as follows
"wiiurpxtool initialization failed: IO Exception: Server returned HTTP response code: 406 for URL:https://github.com/0CBH0/wiiurpxtool/releases/download/v1.3/wiiurpxtool.zip"
![無題](https://user-images.githubusercontent.com/100421240/155721640-388c9655-9ab2-442f-94dd-6f55809af855.png)

**Comment by BullyWiiPlaza** [comment]
It's fixed now, please re-download the new JAR. 👍

**Comment by ebi-allen** [comment]
I was able to confirm that it was fixed.
Thanks!
